eth/catalyst/api.go

The chances of a collision here are very rare, as the payload ids are used in FIFO order, and one at a time, but it doesn't hurt to update the payload ID computation to match all payload attributes. Long-term these payload IDs may be used for other block building software.

eth/catalyst: update payload id computation [optimism bedrock]

---

consensus/misc/eip1559.go
core/chain_makers.go
miner/worker.go
params/config.go

Make the global eip 1559 adjustment values configurable, and specify with optimism config for bedrock. Fallback to the old global values for non-optimism chains.

Optimism eip 1559 config

---

accounts/abi/bind/backends/simulated.go

Adds additional configurability to the simulator in order to allow us to specify custom genesis config properties.
Fixes the test bugs in https://github.com/ethereum-optimism/optimism/pull/3322.

Make the simulator more configurable

---

accounts/abi/bind/backends/simulated.go
core/rollup_l1_cost.go
core/state_transition.go
core/types/deposit_tx.go
core/types/transaction.go
core/vm/evm.go

This PR:
- Adds `IsDepositTx() bool` to the `Message` interface: for API calls and regular txs going through EVM.
- Adds `IsDepositTx() bool` to the `*Transaction` type: to fit the same rollup message interface as an EVM message, to directly compute rollup tx cost from a tx (as done in the tx pool).
- Cleans up the ordering of the fields/methods to group together the related optimism changes.
- Replace any usage of the previous artificial nonce value check with proper `IsDepositTx` check.
This should fix issue OPB-6 as reported by Sigma Prime.
Fix ENG-2618

Fix OPB-6: use IsDepositTx instead of artificial nonce value check

---

accounts/abi/bind/backends/simulated.go
consensus/beacon/consensus.go

This PR:
- Adds a `consensus.Engine` option to the simulated backend. This enables us to use the proof of stake consensus.
- Note that the proof of stake consensus does not have the same timestamp range issues, unlike clique and ethash:
- clique header verification checks timestamp with 0s margin
- ethash header verification checks timestamp with 15s margin
- Since the simulated backend uses a 10s block time internally, the above is a big issue, causing blocks to get stuck until the `futureBlocks` in the `Blockchain` is emptied. This used to force us to wait until the background job clears that queue, and the polling was slow with a second interval.
- Updated the `Commit` in simulated backend to immediately index the transactions. The receipts and block are indexed …

Simulated backend - enable proof of stake consensus type and fix performance issue

---

cmd/geth/main.go
cmd/utils/flags.go
eth/backend.go
eth/ethconfig/config.go

Adds a flag for specifying the rpc endpoint to query historical data.
#12 builds on this PR.
**Metadata**
- Fixes ENG-2887

config: Add historical-data rpc fallback

---

cmd/geth/main.go
cmd/utils/flags.go
eth/api_backend.go
eth/backend.go
eth/ethconfig/config.go
internal/ethapi/backend.go
internal/ethapi/transaction_args_test.go
les/api_backend.go
les/client.go

This PR builds on #10. 
Adds two methods to the `EthAPIBackend` and `LesApiBackend`: 
- `GetSequencerRPCService`
- `GetGenesis`
These methods will be used in a future PR to support redirecting pre-bedrock blocks to a historical node.

Flags and interfaces for historical RPC requests

---

eth/api_backend.go
ethclient/ethclient_test.go
internal/ethapi/api.go
internal/ethapi/backend.go
internal/ethapi/transaction_args_test.go
les/api_backend.go

Updates the `BlockChainAPI.Call()` and `BlockChainAPI.EstimateGas()` methods so that they will attempt to fallback to calling the `HistoricalRPCService` in the event that the block is not found locally. 
In order to handle this cleanly, a new error `ErrHeaderNotFound` was created. 
**Tests**
New tests were added for both methods.

Redirect historical RPC requests

---

eth/api_backend.go
ethclient/ethclient_test.go
internal/ethapi/api.go

Wraps the `ethereum.NotFound` error for error handling in the daisy chain.
This approach should also reduce the diff.

Use the pre-existing ethereum.NotFound error

---

eth/tracers/api.go
eth/tracers/api_test.go
internal/ethapi/api.go

Adds fallback to the Historical RPC endpoint to 
- `debug_traceBlockByNumber`
- `debug_traceBlockByHash`
**Tests**
A test was added for the historical case of `debug_traceBlockByNumber`. No tests yet exist for `debug_traceBlockByHash`, so they will be added in op-e2e instead.

Add historical endpoint to TraceBlockByNumber and TraceBlockByHash

---

eth/tracers/api.go
eth/tracers/api_test.go

This PR builds on #19. 
It adds history support to `debug_TraceTransaction`.
**Tests**
A test case was added for transactions which are not found locally.

Add historical endpoint to TraceTransaction

---

eth/tracers/api.go
eth/tracers/api_test.go

Add historical endpoint to TraceCall
**Tests**
A test was added to verify that the call happens to the historical RPC, and that it's response is returned correctly.

Add historical endpoint to TraceCall

---

core/state_transition.go
params/config.go
params/protocol_params.go

*Description*
Reduce the amount of consensus critical config by hardcoding the addresses that fees pay out to. The final recipient of the fees can now be controlled at the application layer, by the admin of the proxy sitting at the addresses that fees are paid out to.

op-geth: add hardcoded addresses for fee payouts

---

eth/state_accessor.go
eth/tracers/api.go

Currently `debug_TraceTransaction` panic's in two separate scenarios: if the transaction doesn't exist (or hasn't yet been included in a block), or if the `--rollup.historicalrpc` argument is not provided. This PR fixes both those scenarios.
**Tests**
I've tested both scenarios using the Optimism bedrock devnet.
Transaction doesn't exist panic:
```
ERROR[11-18|01:13:55.892] RPC method debug_traceTransaction crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 2271 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
github.com/ethereum/go-ethereum/rpc/service.go:199 +0x89
panic({0x133a420, 0x20e90d0})
runtime/panic.go:838 +0x207
github.com/ethereum/go-ethereum/core.(*StateTransition).innerTransitionDb( …
```

Fix panics in debug_TraceTransaction

---

core/block_validator_test.go

I modified the ethash version of the test to iterate over `block` rather than `preBlocks` when it was computing the total difficulty of the merge point. This is in line with the isClique version of test & avoid an issue where the td was 0 (i.e. a genesis transition) rather than occurring after the preBlocks and before the postBlocks.
**Metadata**
- Fixes ENG-3052

Fix testHeaderVerificationForMerging under Ethash

---

eth/tracers/api.go

We noticed `op-geth` panic'ing when trying to use the debug tracing API with high concurrency. This is due to a `fatal error: concurrent map read and map write` in the state DB from the `L1CostFunc`.
This PR uses the copy of the state DB that's passed into the jobs channel as part of the task struct.
**Tests**
This is hard to reproduce... would love some pointers on regression testing.

[Bug] Fix concurrent map write panic

---

cmd/geth/config.go
cmd/geth/main.go
cmd/utils/flags.go
core/genesis.go
eth/backend.go
eth/ethconfig/config.go
params/config.go

This enables two overrides: the bedrock fork block & the optimism config
being set. The optimism override uses the default EIP 1559 parameters.
These make it easy to setup a node in optimism mode & have a configurable
bedrock block.
All of the rules accessors are also helpful for checking which mode the
node is running in.

Optimism Bedrock fork block + override

---

core/types/legacy.go

Part of the boot process looks at receipts in the database to determine which schema is used. When booting with legacy optimism style receipts in the database, an error message is shown on boot. This error message doesn't do anything, but this commit fixes the problem. If when checking for legacy receipts and `true` is returned, then geth will shutdown and tell the user to run a migration command to migrate to newer style receipts. We return `false` to prevent geth from shutting down. Further investigation is needed to ensure that having these receipts in the database won't cause any issues, we may need to migrate them similarly to the tool that the geth team wrote to upgrade the receipt serialization.

fix: startup receipt deser

---

miner/worker.go

When the pending block is computed, it would previously use the full gas limit. When the eip 1559 elasticity is high, this can be too much gas for some resource constrained devices. And every tx processed into the pending block is re-applied if it's not included. This can cause high block production lag as seen in opcraft. To mitigate this, we can allow the user to set the pending gas limit with the existing miner gas limit flag, which is non-functional in optimism otherwise, since the gas limit is set by the system configuration.
The `prepareWork` method has two call paths:
- the engine API: we always specify the exact gas limit we want here
- the pending-block background work: the generation parameters are largely all left unspecified, including the gaslimit. If it's …

optimism: user can set pending block gas limit

---

core/rawdb/accessors_metadata.go
eth/backend.go
params/config.go

Fixes minor issues encountered in goerli bedrock upgrade:
- The banner didn't display because clique config was set. Prioritize printing optimism consensus mode, if specified.
- The clique config shouldn't be there in the first place: if optimism config is specified, we remove the clique data (clique config was a holdover from legacy pre-bedrock geth workarounds).
- The networkid flag was missed by many users. Let's just default it to the chain ID.
Example of clique network in banner, during debugging before fixes:
Tested against goerli optimism bedrock network.
```
curl http://127.0.0.1:8545   -X POST   -H "Content-Type: application/json"   --data '{"method":"net_version","params":[],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":"420"}
```

optimism: minor goerli fixes - banner, clique config, networkid

---

internal/ethapi/api.go

Adds the following RPC endpoints to the daisychain usage:
- `eth_getBalance`
- `eth_getProof`
- `eth_getCode`
- `eth_getStorageAt`
- `eth_getTransactionCount`
Closes ENG-3203

op-geth: more daisychain routing

---

cmd/geth/main.go
cmd/utils/flags.go
eth/backend.go
eth/ethconfig/config.go
ethclient/ethclient_test.go
les/client.go

This flag lets one configure the initial timeout of RPC requests to the historical RPC service.
Fixes ENG-3294

optimism: Add --rollup.historicalrpctimeout flag

---

core/types/transaction_marshalling.go
core/types/transaction_marshalling_test.go

Fixes `Transaction.UnmarshalJSON` to return an error if the `gas` field is not specified or is `null` in the JSON.
**Tests**
Added tests to confirm JSON is rejected if any of the required deposit tx fields are missing.
**Invariants**
Unmarshalling tx JSON never panics.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3335/sherlock-276-panic-when-decoding-a-malformed-deposit-transaction-json

fix: Validate gas field specified when unmarshalling deposit tx JSON

---

core/types/transaction_marshalling.go
core/types/transaction_marshalling_test.go
internal/ethapi/api_test.go

Allow either nil or 0 values for v, r, s and GasPrice. Add a test to ensure deposit tx json can be round-tripped.
This is required for #40 which starts to set these values to 0 instead of nil.
**Tests**
Added a test to confirm that deposit tx can be parsed from the JSON it serializes so at least the serialise and unserialise code is compatible.
**Metadata**
First step required for https://linear.app/optimism/issue/CLI-3281/spike-work-out-differences-between-gettransactionbyhash-response-on

Make deposit tx parsing more flexible

---

.github/workflows/pages.yaml
fork.yaml

This updates the `fork.yaml` with the slight changes in package paths of v1.11.2 and diff updates we made since forkdiff was introduced.
This is blocked by #46 - we should disable it on the old branch first.
**Metadata**
Fix CLI-3425

forkdiff: update fork-diff to generate post-v1.11.2 rebase diff (`optimism` branch)

---

eth/tracers/api.go

Fix linter by removing the unused `errTxNotFound` variable.

Remove unused variable to fix linter

---

cmd/geth/config.go
cmd/geth/main.go
cmd/utils/flags.go
core/genesis.go
eth/backend.go
eth/ethconfig/config.go
params/config.go
params/config_test.go

Adds the regolith hard fork to `ChainConfig` and a CLI option to override the fork timestamp. There is currently no changes implemented with Regolith, just the config. This config will then act as the feature toggle that allows merging the actual regolith changes in small, incremental steps safely as they won't be enabled until the hard fork is actually scheduled.
**Tests**
Added tests for the rules logic around when regolith is enabled.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3395/update-chainconfig-to-include-regolith

feat: Add support for Regolith in chain configuration

---

internal/ethapi/api.go
internal/ethapi/api_test.go

When serializing deposit transactions for RPC responses, provide 0 values for v, r, s and gasPrice instead of null to improve compatibility with existing parsing code.
**Tests**
Added a unit test for these default fields and the deposit specific ones to cover the behaviour changed from geth.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3281/spike-work-out-differences-between-gettransactionbyhash-response-on
With these changes deposit transactions are now reported as:
```json
{
"jsonrpc": "2.0",
"id": 2,
"result": {
"blockHash": "0x6b2d65121124c6742664cfc6f11a48f551ecebaec2a42a1da48fae75dfe54851",
"blockNumber": "0x4165bc",
"from": "0x6197d1eef304eb5284a0f6720f79403b4e9bf3a5",
"gas": "0x208620",
"gasPrice": "0x0",
"hash": …
```

Include 0 values for v,r,s and gasPrice on deposit transactions

---

core/state_processor.go
core/types/gen_receipt_json.go
core/types/receipt.go
core/types/receipt_test.go
internal/ethapi/api.go

Store the actual nonce used for deposit transactions in the receipt. It is then used when returning the receipt via the JSON-RPC API as a `DepositNonce` field and when calculating the `ContractAddress` for contract creation transactions.
The existing deposit transaction type is used, but after regolith its receipt has an additional rlp field that reports the Nonce.  Implementation-wise this is marked as an optional field so deposits from both before and after the fork can be parsed. The state transition guarantees that the nonce is only present post-regolith.
**Tests**
* Check that deposit tx rlp from pre-bedrock (without nonce) is unchanged and can be parsed by the new code
* Check that receipts can be roundtrip for storage and consensus
* Check that deposit tx receipt …

Regolith: Store nonce in deposit transaction receipts

---

core/error.go
core/state_transition.go

Once the Regolith hard fork activates, reject any deposit tx with `IsSystemTx: true`.
**Tests**
Not covered in op-geth repo but will be checked via e2e tests with https://github.com/ethereum-optimism/optimism/pull/4931
Builds on https://github.com/ethereum-optimism/op-geth/pull/52
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3414/opgeth-regolith-reject-system-transactions

Reject system deposit transactions in Regolith

---

params/config_test.go

Fix the typo in config test name
**Tests**
N/A
**Invariants**
N/A

Fix Regolith test name typo

---

core/types/deposit_tx.go
core/types/transaction.go
core/types/transaction_marshalling.go
eth/api.go
internal/ethapi/api.go
internal/ethapi/api_test.go

When returning deposit transaction information from the JSON-RPC API, the actual nonce used is loaded from the receipt and included in the response.
**Tests**
Will be tested via e2e tests in https://github.com/ethereum-optimism/optimism/pull/4931
There's a complication here because while tx serialisation is done via a custom `RPCTransaction` type that has a `Nonce` field, deserialisation is done back into the same `TxData` type (`DepositTx` in this case).  Since `DepositTx` doesn't have a `Nonce` field, there's nowhere to store the nonce from the API so it becomes unavailable to anyone using the client api client which happens to include our e2e tests.  To get around this, I've introduced a `depositTxWithNonce` wrapper which adds the `Nonce` field if …

Include the actual nonce used when returning deposit tx from the JSON RPC API

---

core/blockchain.go

Log a warning when starting op-geth on an Optimism chain without a regolith timestamp set. 
Should hold off merging this until we're getting close to setting a timestamp for Regolith so users aren't warned about something they can't fix too much.

Log a warning when optimism enabled but regolith not scheduled

---

core/genesis.go
params/config.go

Schedules Regolith on Optimism Goerli at 1679079600 which is March 17, 2023 @ 7:00:00 pm UTC / March 17, 2023 12:00 MST
**Metadata**
- Part of https://linear.app/optimism/issue/CLI-3396/add-regolith-fork-time-for-gorli-to-op-geth

core: Schedule Regolith on Optimism Goerli at 1679079600

---

.circleci/config.yml

Build amd64 & arm64 docker images. The docker build step is now really slow because it is doing a full emulation. I attempted an approach like https://github.com/ethereum-optimism/optimism/pull/5018, but geth does not play well with being cross compiled inside docker. I believe it is an issue with cgo.
I tested this by bypassing the branch condition check.
**Metadata**
- Fixes CLI-3530

Multi-arch docker build

---

internal/ethapi/api.go
internal/ethapi/api_test.go

Omit the `isSystemTx` field from JSON-RPC unless the value is actually true.  `isSystemTx` was already optional, defaulting to false, when parsing so this is backwards compatible.  The `IsSystemTx` field is still always included RLP so this isn't a consensus affecting change.
**Tests**
Added test to confirm IsSystemTx is nil rather than false.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3545/omit-issystemtx-from-json-rpc-responses-when-false

ethapi: Omit isSystemTx: "false" from JSON-RPC responses

---

core/rawdb/accessors_chain.go
core/rawdb/accessors_chain_test.go

eth_getLogs RPC parses the receipts using its own copy of storedReceiptsRLP. For RLP decoding to work it needs to include optional fields for each of the additional values in deposit tx receipts and legacy OVM receipts. These fields are never actually used - only the `Log` field is accessed.
**Tests**
Added a `DepositNonce` value to one of the receipts in the existing test for `ReadLogs`.
Currently unable to write automated tests for parsing of legacy receipts as we don't have a way to insert them into the database except by doing a migration. Tested that manually against Goerli migrated database.
**Metadata**
- https://linear.app/optimism/issue/CLI-3555/error-from-eth-getlogs-when-regolith-enabled

core/rawdb: Add DepositNonce and legacy fields to copy of storedReceiptRLP in accessors_chain

---

core/state_transition.go

Fixes and issue where `eth_call` would fail with errors like:
```
Error:      	Expected nil, but got: &fmt.wrapError{msg:"failed to get number: err: insufficient funds for gas * price + value: address 0x0000000000000000000000000000000000000000 have 1 want 22316 (supplied gas 9223372036854775807)", err:(*rpc.jsonError)(0x14008999950)}
```
Prior to https://github.com/ethereum-optimism/op-geth/commit/cde9c26c4888d3676d2162996b3c1e6768bd08c5 `l1CostGas` would always be set to 0 in both `NewMessage` and simulated.go's `callMsg`. Now both those places create a new `RollupGasData` struct and then the gas used calculation is performed by its `DataGas` method. As a result, the real L1 gas cost winds up being used instead of being hard coded to 0.
Now L1 costs are ignored entirely …

core: Don't require L1 cost to be paid when simulating transactions

---

eth/tracers/api.go

We are experiencing a panic in `debug_traceBlockByHash` due to a missing `L1CostFunc`. This PR sets this.
An alternative direction might be to refactor `NewEVMBlockContext` to accept a `types.L1CostFunc`... but this seems fine for now.
**Tests**
No tests added. Very similar PR to #27.
Panic:
```
goroutine 59443519 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
github.com/ethereum/go-ethereum/rpc/service.go:199 +0x89
panic({0x17a3f20, 0x2841670})
runtime/panic.go:884 +0x212
github.com/ethereum/go-ethereum/core.(*StateTransition).innerTransitionDb(0xc01ea81400)
github.com/ethereum/go-ethereum/core/state_transition.go:477 +0x1026
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc01ea81400) …
```

Add missing L1CostFunc set

---

accounts/abi/bind/backends/simulated.go
core/evm.go
core/state_prefetcher.go
core/state_processor.go
eth/api_backend.go
eth/state_accessor.go
eth/tracers/api.go
eth/tracers/api_test.go
les/api_backend.go
les/odr_test.go
les/state_accessor.go
light/odr_test.go
tests/state_test.go
tests/state_test_util.go

Moves creation of `L1CostFunc` into `NewEVMBlockContext` so that the constructor always returns a fully formed object.
Follow up to #70 to make it less likely to have similar bugs in the future - especially when pulling in upstream changes which may add new places that call `NewEVMBlockContext` as those will now result in compile failures rather than runtime crashes.
While this looks like a large changeset, in all but a couple of tests we're just replacing a separate set of `L1CostFunc` with two new params to `NewEVMBlockContext`.

core: Set L1CostFunc in NewEVMBlockContext

---

.circleci/check-releases.sh
.circleci/config.yml

Adds a daily check for new upstream Geth releases that haven't yet been merged into op-geth. Will post to slack when such a release is found.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-3688/monitor-upstream-geth-releases

Add upstream release check

---

fork.yaml

Point the diff tool to the upstream v1.11.4 commit as base, to clean up the op-geth.optimism.io site diff
We'll have to update it again when we merge the v1.11.5 PR - #74

optimism: fork.yaml update upstream base commit

---

.circleci/ci-docker-tag-op-geth-release.sh
.circleci/config.yml

This uses the same script from the monorepo to tag the latest docker image.

ci: Tag latest build

---

core/genesis.go
params/config.go

Sets Base Goerli Regolith upgrade to occur on Thursday April 27, 2023 @ 5:00:00 pm UTC, 1:00:00 pm EST, 10:00:00 am PST
**Tests**
Ran local devnet with Base Goerli chain identifier (`84531`) and verified that op-geth set the correct timestamp. 
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 "Release Notes"

Schedule Regolith on Base Goerli at 1682614800

---

params/config.go

Updates Base Goerli Regolith upgrade to occur on Thursday May 4, 2023 @ 5:00:00 pm UTC, 1:00:00 pm EST, 10:00:00 am PST. This update is necessary due to the planned Regolith upgrade failing to be applied due to a misconfigured sequencer.
**Invariants**
For changes to critical code paths, please list and describe the invariants or key security properties of your new or changed code.
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 "Release Notes"

Update goerli regolith hardfork time

---

fork.yaml

Cleans up the https://op-geth.optimism.io diff site by changing the upstream reference to match the v1.11.6 changes introduced in #88

fork.yaml: update fork diff for v1.11.6

---

core/types/receipt.go
core/types/receipt_test.go

Adds the L1 overhead to the `l1GasUsed` reported for L2 transactions.  This restores the invariant that `l1Fee = l1GasPrice * l1FeeScalar * l1GasUsed` as it did pre-bedrock.
**Tests**
Added tests to check derivation of L1 gas related fields.
**Invariants**
`l1Fee = l1GasPrice * l1FeeScalar * l1GasUsed`
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 "Release Notes"

core/types: Include overhead in the L1GasUsed for receipts.

---

cmd/geth/main.go
cmd/utils/flags.go
eth/api.go
eth/api_backend.go
internal/ethapi/api.go
miner/miner.go
miner/worker.go

This fixes the pending-block behavior to be more compatible with pre-bedrock assumptions: requests for the "pending" block/header get served the "latest" block. This prevents transactions from the tx-pool from being revealed before they are committed to by the sequencer
Additionally this updates other lesser used API endpoints that utilize the "pending" mining state as well:
- debug-namespace methods do not serve state or receipts for the pending block, if not available like in the rollup case.
- the pending-state in graph-QL queries (as hit by `StateAndHeaderByNumberOrHash`) continues processing as "latest" state when the pending state is not available, like in the rollup case.
And to prevent unnecessary pending-block computations, the worker in the `miner` package is …

miner,eth: latest block as pending block on rollup

---

cmd/geth/main.go
cmd/utils/flags.go
core/txpool/txpool.go
core/txpool/txpool_test.go

Adds a `--txpool.journalremotes` option that ensures all transactions are written to the journal (if enabled) instead of only local ones.  When reloading transactions after a restart all loaded transactions are treated as remote.
This is designed to be used with `--txpools.nolocals` where there are no local transactions but its desirable to have the transaction pool content preserved across restarts.
**Metadata**
- Fixes https://linear.app/optimism/issue/CLI-4060/support-journalling-remote-transactions

core/txpool: Support journaling remote transactions with --txpool.journalremotes

---

cmd/geth/main.go
cmd/utils/flags.go
core/txpool/txpool.go
core/txpool/txpool_test.go

Backports https://github.com/ethereum-optimism/op-geth/pull/97 to the v1.101105 release branch.
**Metadata**
- https://linear.app/optimism/issue/CLI-4060/support-journalling-remote-transactions

core/txpool: Support journaling remote transactions with --txpool.journalremotes (Backport)

---

eth/gasprice/gasprice.go
eth/gasprice/optimism-gasprice.go
eth/gasprice/optimism-gasprice_test.go

Provides a new max priority fee (aka "tip cap") suggestion algorithm appropriate for chains like Optimism with a single known block builder. In the typical case, which results whenever the last block had room for more transactions, the algorithm returns a minimum allowed priority fee. Otherwise it returns 10% over the median effective priority fee from the last block.
**Tests**
Includes unit tests covering at & under capacity cases.
This fixes an issue we are encountering on Base goerli testnet, and I imagine affects other chains where blocks are not (yet) near full. Once a node sees a few transactions with a given priority fee, it effectively locks in that first-seen priority fee as its tip estimate even when there is plenty of blockspace. Without a …

implement more accurate & predicable priority fee suggestion algorithm for chains like Optimism

---

internal/ethapi/api.go

Pre-bedrock relayed txs do not have a signature. When served in the RPC the chain ID should not be computed from the signature values, but rather be set from the chain config, to ensure it's stated correctly in the RPC result. The legacy l2geth didn't include the chain ID in the response at all, but we do want it to be compatible with the latest API spec that includes it.
**Tests**
Fixes an API result of legacy data, may need a new testing strategy for l2geth data, but this change is simple enough that we can test-run it with:
```
cast rpc --rpc-url=http://127.0.0.1:8745 eth_getTransactionByHash 0xe1fb9e9031d966b707e154e228ad135956df7d3971bc40a6906848a81a8a98dd
```
Which previously recorded `"chainId":"0x7fffffffffffffee"` but should now be `"chainId":"0xa"`
**Metadata** …

optimism: set chain-ID of pre-bedrock relayed txs

---

internal/ethapi/api.go

Backport: setting chain-ID of pre-bedrock transactions

---

core/types/transaction_marshalling_test.go
core/types/transaction_signing.go

When the nonce of a deposit transaction is non-nil, the inner transaction is decoded as type `depositTxWithNonce`. Hence when getting the sender of such transactions, the type of the inner transaction should be checked.
**Tests**
Added test in core/types/transaction_marshalling_test.go
**TODOs**
[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 "Release Notes"

Fix sender of deposit transactions

---

miner/worker.go

Change min-recommit interval to 100ms to experiment with more block-building iterations and tx-inclusion of later txs.
This only affects the sequencing code.
**Tests**
Geth doesn't have a fake clock util here, and CI is laggy, so timing should be tested on devnet.

miner: change min recommit interval to 100ms

---

miner/worker_test.go

Fixes simple test cases that were broken in #102
The min recommit interval is now lower than the test case expects as lower bound, meaning that the 500ms doesn't get clipped to 1s anymore.

miner: adjust test to handle updated min-recommit interval

---

eth/handler.go
eth/protocols/snap/handler.go

Hi! This is Tei from Test in Prod.
This PR is a small fix for Geth’s snap sync for op chains.
- Geth reads account bytecodes with prefixed keys during the snap-sync. However, the bedrock genesis DB saves bytecodes with the legacy key without prefixes. **This PR adds a fallback logic for the legacy keys** to serve bytecodes for snap sync.
- FYI, this fallback had been removed by the Geth team (https://github.com/ethereum/go-ethereum/pull/24276/files#diff-048b7cda1c653b08f9eea9ee81ac5937ea8326556bceffd1ca1a3059bc24dbfdR470) for optimization.
- New nodes that are synced using snap-sync will have prefixed keys in their DB, so eventually we can follow the deprecation process.
- Geth starts snap sync only if the current chain head is at the genesis block. **This PR allows snap …

Support snap sync for OP chains

---

cmd/devp2p/internal/ethtest/snap.go
core/blockchain_reader.go

Due to the way the v1.12.0 changes and snap-sync support changes landed, this build issue was caused.
```
eth/protocols/snap/handler.go:472:32: chain.ContractCode undefined (type *core.BlockChain has no field or method ContractCode)
```
We need the legacy contract-code without prefix to support serving sync from older databases that do not have the prefix as part of the contract-code key.
This effectively undoes https://github.com/ethereum/go-ethereum/pull/27186

core: reinstate ContractCode function to support snap-sync from legacy DB nodes

---

fork.yaml
internal/ethapi/api.go

Export the chain-config for debug / dev-tooling purposes. Since the chain-config format is technically node-dependent, it's only exposed on the debug namespace.
Indexers depend on the fork block numbers to post-process the chain, so this makes it easy to access, and generic between all op-stack chains. This prevents having to lookup external sources or manual database inspection work.

internal/ethapi: add chain-config debug RPC method

---

p2p/server.go

The `discmix` that the dial scheduler pulls enodes from was not getting node records from discv5.
When discv4 is disabled, but discv5 is enabled, and operating on a private network (no public dns based discovery), the geth node was able to peer manually, and log things about discovery, but wasn't dialing discovered records.

p2p: add discv5 to the discmix to dial nodes with

---

cmd/utils/flags.go
core/genesis.go
core/superchain.go
core/superchain_test.go
go.mod
go.sum
params/config.go
params/superchain.go

To make OP-Stack chain configurations available across OP-Stack client implementations, we are experimenting with a "superchain-registry": one place that hosts all superchain configurations, which can then be embedded into the software for convenience & OP-Stack wide rollout of config changes.
These config utils are optional functionality (`geth init` with a custom genesis setup will always work, chains can be registered after launch at any time), but aims to increase convenience of running a node.
Using the registry data, a `core.Genesis` can be created from the embedded block-contents and genesis-allocation. This depends on tooling to build the genesis-allocation from a list of contract-references + contract bytecode registry: we need to deduplicate the many predeploy …

params: source chainConfig and genesis from superchain-registry

---

build/ci.go
params/version.go

As reported in https://github.com/base-org/node/issues/75, `op-geth` does not keep the version variables up-to-date with the released version tag.
This PR threads the env.Tag calculated in the `build/ci.go` script to an internal variable in the `params` package, and sets the `OPVersion*` variables to the relevant values.
**Tests**
Tested locally by building and running `geth --version`:
```
> go run build/ci.go install -static ./cmd/geth
```
For a tagged released commit:
```
> build/bin/geth --version
geth version 1.101106.0-stable-b5fecf58
```
For latest on `optimism` branch:
```
> build/bin/geth --version
geth version 0.1.0-unstable-b3c4be01-20230726
```

Set op-geth version at build

---

cmd/geth/main.go
cmd/utils/flags.go
eth/ethconfig/config.go
eth/filters/api.go
eth/filters/filter_system.go
eth/filters/filter_system_test.go

Currently op-stack chains can leak tx pool contents on shared nodes using two methods:
- HTTP call to `eth_newPendingTransactionFilter` and subsequent calls to `eth_getFilterChanges`
- WS `eth_subscribe` to `newPendingTransactions`
This PR disables these two methods by default (returning an error: `pending tx filters are disabled`). It also adds a new flag: `--rollup.allowpendingtxfilters` which optionally enables them. 
**Tests**
Tested running geth locally. Without the option:
```
> curl -d '{"id":0,"jsonrpc":"2.0","method":"eth_newPendingTransactionFilter","params":[]}' -H "Content-Type: application/json" http://localhost:8545
{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"pending tx filters are disabled"}}
> wscat --connect ws://localhost:8546
> { "id": 1, …
```

Disable access to pending txs from filters + subscriptions

---

cmd/utils/flags.go
eth/api_backend.go
eth/backend.go
eth/ethconfig/config.go

Disables the local txpool, so that transactions submitted to the RPC will not get added to the txpool. This is enabled by default flag for any nodes that have `--rollup.sequencerhttp` and not `--mine`, and can be opted-out using `--rollup.enabletxpooladmission`.
**Tests**
No tests added.
We are seeing some MEV issues with node providers with shared txpools.

Disable tx admission into the txpool if `--rollup.sequencerhttp` is set

---

cmd/geth/main.go
cmd/utils/flags.go
eth/ethconfig/config.go
eth/gasprice/gasprice.go

This decrease the GPO default minimum suggested fee to 0.001 GWEI from 0.1 GWEI and also make this value configurable via the `--gpo.MinSuggestedPriorityFee` command line option.

Decrease GPO min suggested fee & make it configurable

---

cmd/geth/main.go
cmd/utils/flags.go
eth/backend.go
eth/catalyst/api_test.go
eth/catalyst/superchain.go
eth/catalyst/superchain_test.go
eth/ethconfig/config.go
params/superchain.go
params/superchain_test.go

Part of the protocol-versioning signal mechanism, to alert nodes when they are running outdated software that does not support the latest protocol.
Add `--beta.rollup.halt=major|minor|patch|none` (disabled by default) to opt in to halting when noticing a required protocol change through a signal from a rollup node via the Engine API.
Fix CLI-4209

introduce engine_signalSuperchainV1

---

cmd/utils/flags.go

This functionality is going out of beta, into regular release-candidate and release cycle.

flags: remove beta prefix from rollup.halt flag

---

Makefile

When changing fork.yaml, it is useful to check the updated output without relying on CI.
Feel free to close the PR without comment, if this is not useful to you.

Add make target to create local forkdiff output

---

core/types/receipt.go

The upstream v1.12.2 update refactored the `Receipts.EncodeIndex` method so there was a single call to prefix the receipt tx type before switching on the tx type rather than needing code to write the type prefix for each separate type.
The deposit tx type case is added in our diff but wasn't updated to _not_ write the prefix so wound up with a duplicate prefix and so calculated the incorrect receipt root.

Do not prefix deposit tx type twice when calculating receipt trie root.

---

cmd/utils/flags.go
go.mod
go.sum
params/config.go
params/superchain.go

- Update superchain-registry, to include chaosnet configuration
- Update regolith exceptions: Chaosnet is another edge-case. If we have any more of these we can add it to the registry instead, but with op-goerli/base/devnet/chaosnet I think we are done. (and there are `rollup.json` specific exceptions to the chaosnet too, compared to prod chains).
- Update EIP1559Elasticity exception
Testing the chaosnet config:
```bash
mkdir tmp
curl https://storage.googleapis.com/chaos-chain/genesis.json > tmp/genesis.json
go run ./cmd/geth init --datadir=tmp/gethdata tmp/genesis.json
go run ./cmd/geth dumpgenesis --datadir=tmp/gethdata > tmp/dump_genesis.json
diff <(jq --sort-keys . tmp/genesis.json) <(jq --sort-keys . tmp/dump_genesis.json)
go run ./cmd/geth dumpgenesis …
```

params: add chaosnet, update superchain-registry

---

params/superchain.go

Fix the devnet config.
Based on chaosnet PR, which fixes the `dumpgenesis` command.
Verify with:
```bash
curl https://storage.googleapis.com/oplabs-network-data/internal-devnet/genesis.json > tmp/devnet_genesis.json
go run ./cmd/geth init --datadir=tmp/devnetdata tmp/devnet_genesis.json
go run ./cmd/geth dumpgenesis --datadir=tmp/devnetdata > tmp/devnet_dump_genesis.json
diff <(jq --sort-keys . tmp/devnet_genesis.json) <(jq --sort-keys . tmp/devnet_dump_genesis.json)
go run ./cmd/geth dumpgenesis --beta.op-network=op-labs-devnet-0-goerli-dev-0 > tmp/superchain_devnet_dump_genesis.json
diff <(jq --sort-keys . tmp/devnet_genesis.json) <(jq --sort-keys . tmp/superchain_devnet_dump_genesis.json)
```
The existing devnets did not adopt the previous malformed superchain-registry sourced …

params: devnet config fix

---

cmd/geth/main.go
cmd/utils/flags.go
core/gen_genesis.go
core/genesis.go
core/superchain_test.go
eth/backend.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go

Adds chain-config override functionality, to upgrade existing chain configs (in DB, from previous runs) with the chain config as defined in the superchain-registry.
This is optional, and behind a beta feature-flag for rollout: `--beta.rollup.superchain-upgrades`
This also fixes some formatting in the genesis config for CI, which appeared to be formatted incorrectly due to prior merges.
**Tests**
Test that with `overrides.ApplySuperchainUpgrades` the superchain-registry chain-configuration is applied to the local chain configuration.
**Metadata**
Fix https://github.com/ethereum-optimism/client-pod/issues/73

superchain: beta feature flag for overriding chain-config with superchain-registry

---

core/rawdb/accessors_chain_test.go
core/state_processor.go
core/types/receipt.go
core/types/receipt_test.go
internal/ethapi/api.go
internal/ethapi/api_test.go

Changes the post-Canyon deposit tx receipt encoding for the receipt-root calculation to include the deposit nonce, while preserving old behavior for pre-Canyon deposit txs with deposit nonces. Adds an optional version number to the deposit receipt consensus encoding that is specified only after Canyon hardfork.
**Tests**
Added test to confirm that legacy behavior of EncodeIndex for post-Regolith / pre-Canyon receipt hashing is maintained, while the post-Canyon behavior correctly includes the nonce and matches the behavior of MarshalBinary.
Existing receipt tests that accepted deposit txs all extended to test receipts both with & without deposit receipt version.
**Metadata**
- Fixes https://github.com/ethereum-optimism/op-geth/issues/144
- …

post-Canyon receipt-root deposit tx hashing fix

---

cmd/geth/main.go

This now checks if the `--beta.op-network` flag is set & then further checks if it is a mainnet network or a testnet. If it is a mainnet network, the cache sized is bumped to 4 gigs.
**Tests**
None. Not even manual.
**Metadata**
- Fixes #155

Bump the geth cache on OP stack mainnet chains

---

eth/catalyst/superchain.go
eth/catalyst/superchain_test.go
params/superchain.go
params/superchain_test.go

`v3.1.0` should be considered *higher* than `v3.1.0-1`.
And the version difference should be reported accurattely, so that there's differentiation between major/minor/patch pre-release differences.
**Tests**
Adds new test cases to cover the different ways A can be ahead of B. The test-runner automatically tests the inverse too, to cover the outdated-cases.

params: handle protocol-version semver prerelease edge-case in version comparison

---

cmd/geth/main.go
cmd/utils/flags.go
params/superchain.go

- Promote `--beta.op-network` to `--op-network`  (keep `beta.op-network` as alias for compatibility)
- Improve `--op-network` usage description, with shortlist of options:
```
--op-network value, --beta.op-network value                                    ($GETH_OP_NETWORK)
Select a pre-configured OP-Stack network (warning: op-mainnet and op-goerli
require special sync, datadir is recommended), options: base-goerli,
base-mainnet, base-sepolia, op-goerli, op-labs-chaosnet-0-goerli-dev-0,
op-labs-devnet-0-goerli-dev-0, op-mainnet, op-sepolia, pgn-mainnet, pgn-sepolia,
zora-goerli, zora-mainnet
```
~Depends on #148 (fixes CI, and implements remaining beta functionality).~
**Metadata**
Fix https://github.com/ethereum-optimism/client-pod/issues/82

op-network option: promote from beta stage & apply chain-config overrides

---

params/superchain.go

Update the protocol-version support param, now that the superchain-parameters (all opt-in, no breaking changes) functionality is completely available.

params: update op-stack protocol version to v3.1.0

---

cmd/utils/flags.go

Promote `rollup.superchain-upgrades` flag out of beta.

cmd: rollup.superchain-upgrades out of beta

---

cmd/evm/internal/t8ntool/transition.go
consensus/misc/eip1559/eip1559.go
consensus/misc/eip1559/eip1559_test.go
core/chain_makers.go
core/state_processor_test.go
core/txpool/blobpool/blobpool.go
core/txpool/blobpool/blobpool_test.go
core/txpool/legacypool/legacypool.go
eth/gasprice/feehistory.go
graphql/graphql.go
internal/ethapi/api.go
miner/worker.go
params/config.go
params/superchain.go

This adds implements changing the EIP 1559 denominator from 50 to 250 with the Canyon network upgrade. This adds the explicit timestamp to `CalcBaseFee`. In some cases the base fee may not be accurate if the exact timestamp of the block is not known.
**Tests**
Unit tests. Verified the values manually.
**Metadata**
- Fixes #143

Change EIP 1559 Denominator with Canyon

---

core/types/gen_receipt_json.go
core/types/receipt.go
core/types/receipt_test.go

Make JSON marshaling/unmarshaling of receipts handle deposit nonce & new deposit receipt version. 
"go generate" was used to regenerate gen_receipt_json.go which appeared to have been manually edited before.
**Tests**
modified receipt json marshal/unmarshal test to confirm receipt root computation is not affected by json encoding
Looks like deposit nonce never was included in the json serialization of a deposit transaction, but since the value wasn't previously being used in receipt hash generation (due to a different bug) this wasn't ever detected.
**Metadata**
- Fixes #[Link to Issue]

fix receipt json marshaling/unmarshaling

---

consensus/misc/create2deployer.go
consensus/misc/create2deployer_test.go

We aligned on removing any branching logic that involves chain ID from the state transition function. This means removing the chain ID conditional for the `create2deployer` deployment introduced in #126. We also removed the `GetCodeSize` check which means the code is overridden on all op-stack chains.
**Tests**
Updated tests.

Remove ChainID + GetCodeSize check from create2deployer precompile deployment

---

consensus/misc/eip1559/eip1559_test.go
core/genesis.go
go.mod
go.sum
params/config.go
params/superchain.go

This is the final touches for Canyon. It enables it via the superchain and includes the baked in devnet activation. This also renames EIP1559DenominatorPostCanyon to EIP1559DenominatorCanyon. Lastly, it activates Shanghai at the same time as Canyon.
**TODO**: Wait until https://github.com/ethereum-optimism/superchain-registry/pull/28 is merged & pull in the tip of the superchain registry.
**Tests**
Manually tested that a local registry was pulling in the right values & that the override was working correctly.

Enable Canyon via superchain in op-geth

---

params/config.go
params/superchain.go

With the removal of `--override.regolith` with #133, Base needs a way to opt-in to the regolith override for our goerli devnet. This PR hardcodes the timestamp we used.
**Tests**
No tests added.

Add regolith override time for base goerli devnet

---

core/genesis.go

Running geth with `--rollup.superchain-upgrades` but no `--op-network` will panic in the superchain config overrides code, because `genesis` is `nil`. This PR fixes that codepath.
**Tests**
No tests added, hotfix for canyon hardfork today.
We are seeing this on our sepolia devnet, which is not yet part of the superchain config.

Fix potential nil pointer dereference panic in superchain overrides

---

params/config.go
params/superchain.go

We opted in to the superchain params, which caused a node halt due to incorrect base fee change validation.
This PR adds the correct `EIP1559Elasticity` overrides for Base goerli + sepolia.
**Tests**
No tests added.
Log:
```
########## BAD BLOCK #########
Block: 1485959 (0x5ea64e70db7d39a314dc63776e983e37638104a14ab100c8d60371da9f71bca9)
Error: invalid baseFee: have 52, want 51, parentBaseFee 50, parentGasUsed 7636391
Platform: geth (devel) go1.21.3 amd64 linux
VCS: 4a3209b4-20231027
Chain config: &params.ChainConfig{ChainID:84532, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:0, …
```

Set base testnets elasticity

---

event/subscription.go
event/subscription_test.go

Cherry-pick changes from https://github.com/ethereum/go-ethereum/pull/28359/ to fix deadlock affecting op-node shutdown.
**Metadata**
- https://github.com/ethereum-optimism/optimism/issues/8086

event: fix Resubscribe deadlock when unsubscribing after inner sub ends

---

cmd/geth/config.go
cmd/geth/main.go
cmd/utils/flags.go
core/genesis.go
eth/backend.go
eth/ethconfig/config.go
params/config.go

Define interop hardfork in chain-config, to attach conditional interop functionality to.
**Metadata**
Fix https://github.com/ethereum-optimism/interop/issues/27

params: interopTime configuration and override option

---

params/config.go
params/superchain.go

See https://github.com/ethereum-optimism/optimism/pull/8354
Even though op-geth does not change with the Delta superchain upgrade (as of current pre-release), it does need to signal that it supports the non-change.

params: add note about Delta, update protocol version to indicate Delta pre-release support

---

eth/catalyst/api_test.go
miner/payload_building.go
miner/payload_building_test.go

Remove the global var to change miner behaviour in tests and try a longer sleep for the payload to build.

Remove global variable to change miner behaviour.

---

eth/catalyst/api_test.go
eth/catalyst/queue.go
eth/catalyst/simulated_beacon.go
miner/payload_building.go
miner/payload_building_test.go

Rather than waiting for a fixed amount of time, expose methods to allow waiting for the payload to complete building the first block.

Deterministically wait for payloads to build the first full block

---

eth/catalyst/api_test.go
eth/catalyst/queue.go
eth/catalyst/simulated_beacon.go
miner/miner.go
miner/payload_building.go
miner/payload_building_test.go
miner/worker.go

- Block building is interrupted on a `getPayload` engine api call.
- Empty block is now only built for `NoTxPool` FCU calls, and as before, FCU blocks on building the empty block. This has the advantage that if generating a lot of empty blocks, `getPayload` can immediately be called after `forkchoiceUpdated` to return that empty block.
- If using the tx pool, FCU doesn't block on any block building but returns immediately after creating the payload promise.
- Resolution of the payload promise (`getPayload`) now waits for the first full block to be built, as there is no empty block to return. If at least one block has already been built, as before, it is returned immediately, while block building is interrupted in the background.
**Tests**
Extended the `TestBuildPayload` …

miner: Add block building interruption on payload resolution (getPayload)

---

beacon/engine/gen_epe.go
beacon/engine/types.go
eth/catalyst/api.go

Extend `ExecutionPayloadEnvelope` to return parent beacon block root as discussed in this [specs PR](https://github.com/ethereum-optimism/optimism/pull/8852).
**Tests**
Added a e2e test for this behavior in `op_geth_test.go`. Happy to also port a a similar test here.

Extend execution payload envelope to contain parent beacon block root

---

core/types/receipt.go
core/types/receipt_test.go
core/types/rollup_cost.go
core/types/rollup_cost_test.go

Adds the logic for computing L1 data fee after the Ecotone upgrade.
**Tests**
Added unit tests exercising the new codepaths and tests to make sure appropriate cost function is computed based on the upgrades active in the config. Better aligned the optimism specific receipt tests with those in rollup_test.go.

Ecotone l1 cost function

---

core/txpool/validation.go
core/types/transaction_signing.go
eth/api_backend.go
eth/backend.go
go.sum
params/superchain.go

Changes:
- explicitly disable Blob transactions
- explicitly change signer methods to use London signer instead of Cancun signer
- activate Cancun when Ecotone superchain fork is set
- update superchain-registry dep (for Ecotone rename)
**Tests**
To be tested in op-e2e. Draft PR for now.
**Metadata**
Part of https://github.com/ethereum-optimism/optimism/issues/8701

L2 Cancun support, activate on Ecotone

---

core/types/receipt.go
core/types/receipt_test.go
core/types/rollup_cost.go
core/types/rollup_cost_test.go

Enforce consistency around the variable naming of "baseFee" vs "basefee" with the former being preferred.
Purely syntactical change, no functionality affected.

baseFee consistency related renaming

---

params/config.go

Adds a log for the ecotone time.
**Tests**
No tested added.
Helps for debugging.

Add log for ecotone time

---

internal/ethapi/api.go

Handles the missing fee-scalar attribute; if Ecotone is activated on a block, it will not be there.
This is covered in new op-e2e action testing that covers transactions per fork. (TODO link)

ethapi: handle fee-scalar receipt attribute

---

consensus/beacon/consensus.go
consensus/beacon/oplegacy.go
core/chain_makers.go
core/types/receipt.go
core/types/receipt_test.go
eth/ethconfig/config.go
ethclient/ethclient_test.go
fork.yaml

Handle legacy pre-bedrock block-headers in consensus validation, to support snap-syncing without prior data-dir.
Very experimental. See optimism monorepo PR for context.

Snap Sync: consensus: handle legacy pre-bedrock header verification

---

accounts/usbwallet/hub.go
fork.yaml

This change fixes Ledger hardware wallet discoverability on Macos 14. 
Error:
```
hidapi: failed to open device
```
Debugging the underlying driver I found it actually enumerate 3 interfaces, but go-ethereum usbwallet hub arbitrarily picks one based on the usageID. 
**Tests**
Manually tested
We use this lib in the upstream https://github.com/ethereum-optimism/eip712sign

fix: ledger hardware wallet support on mac

---

core/types/transaction.go

When we sign a blob tx, we omit the blob sidecar. When handling the signed result, we need to re-attach the sidecar.
This adds a setter to allow this, to avoid composing a complete new blob tx with manual full copying of attributes.

core/types: SetBlobTxSidecar to support blob tx tooling

---

internal/ethapi/transaction_args.go
internal/ethapi/transaction_args_test.go

Updates op-geth with the latest version of transaction_args.go from upstream geth.
**Tests**
Also brings in the updated unit tests.

update transaction_args to latest for blob support

---

consensus/beacon/oplegacy.go

This fixes the OP Legacy Consensus engine `VerifyHeaders` function. When `VerifyHeaders` is called, only the first block is stored in the database & the reset are passed in as a slice. We previously called `VerifyHeader` from `VerifyHeaders` which would expect that the block's parent was in the database. This modifies `VerifyHeaders` to check that the first block is in the database & then checks the blocks one by one through the slice.
**Tests**
I have tested this on op-goerli & op-mainnet.

beacon: Fix OP Legacy block hash checks

---

core/txpool/legacypool/legacypool.go
core/txpool/legacypool/legacypool_test.go

This change adds a check to ensure that transactions added to the legacy pool are not treated as 'locals' if the global locals-management has been disabled. 
This change makes the pool enforce the --txpool.pricelimit setting.
**Tests**
This backport PR has tests.
This PR or the upstream commit should be removed when #215 is merged.

core/txpool/legacypool: respect nolocals-setting (#28435)

---

cmd/geth/config.go
cmd/geth/main.go
cmd/utils/flags.go
core/genesis.go
eth/backend.go
eth/ethconfig/config.go
eth/ethconfig/gen_config.go

We already had an Ecotone override flag, but it wasn't used.
**Tests**
Zach will test it in an internal devnet.

all: Add Ecotone override flag

---

.circleci/config.yml

Adds a new CI job which will fail if the contributor forgot to run `go mod tidy`. 
**Tests**
Manual
**Metadata**
- Fixes https://github.com/ethereum-optimism/client-pod/issues/523

ci: add go mod tidy check

---

.circleci/config.yml

Handle deprecated build image on circle https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177

ci: update image to default

---

core/vm/evm.go
core/vm/interpreter.go

Add a config option to override precompiles for Optimism execution.
The usecase for this change is to allow expensive precompiles, such as KZG point evaluation, to be replaced with a version that is more suitable for a given runtime.
For example, in the case of the fault proof program, executing the KZG point evaluation in MIPS32 requires over 15 billion steps. We'd like to offload this expensive execution to the op-program host, where it's much cheaper to execute.
**This change modifies behavior only when `vm.Config.OptimismPrecompileOverrides` is set**.

core/vm: Allow precompiles to be overriden

---

core/genesis.go

On restarts, nodes that had completed snap sync without using a datadir on transitioned networks would re-commit the genesis state. This would set the local block back to the genesis block and wipe away the state after snap sync. Because op-geth is not able to execute the STF pre-bedrock, it is ok to skip storing this data.
**Tests**
Tested on op-goerli.

Skip genesis state check for transitioned networks

---

core/vm/evm.go
core/vm/interpreter.go

Pass the original precompile to the override function. Will allow the override to optionally delegate some functions to the original precompile instead of having to fully replace it.
**Metadata**
- https://github.com/ethereum-optimism/client-pod/issues/628

Pass the original precompile to the override function.

---

core/state_transition.go
eth/tracers/internal/tracetest/flat_calltrace_test.go
eth/tracers/internal/tracetest/testdata/call_tracer/failed_deposit.json
eth/tracers/internal/tracetest/testdata/call_tracer_flat/failed_deposit.json
eth/tracers/native/call.go
eth/tracers/native/call_flat.go

Natively supports the trace call where a deposit fails. Frame will appear empty with a "stop" type and the proper amount of gas used. We will need to document this to make it clear what's going on.
**Tests**
Added test cases.

feat: add new failed deposit trace call frame
